export enum UserServerPermissionEnum {
  OPEN_FOR_ALL = -100000,
  NONE = 0,

  CLIENT_REGISTRATION = 1,
  BATCH_DETAILS = 2,
  AUDIT_REPORT = 3,
  PRODUCTION_REPORT = 4,
  SYSTEM_SETTINGS = 5,
  SERVER_SETTINGS = 6,
  USER_MANAGEMENT = 7,
  THIRDPARTY_SETTINGS = 8,
  HELP = 9

}
